services:
  sillytavern:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "./config:/home/node/app/config"
      - "./data:/home/node/app/data"
      - "./plugins:/home/node/app/plugins"
    restart: unless-stopped
    networks:
      - sillytavern-network

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    depends_on:
      - sillytavern
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl:/etc/ssl
    environment:
      - PORT=8000
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - sillytavern-network

networks:
  sillytavern-network:

